config/routes.rb
Rails.application.routes.draw do
  root 'site#index'
  devise_for :users
  resources :secret_codes, only:[:index, :destroy] do
    collection do
      post :generate
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      cannot :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/codeable.rb
module Codeable
  extend ActiveSupport::Concern

  included do
    attr_accessor :code
    validates_presence_of :code, unless: :admin?
    validate :valid_code?, unless: :admin?

    after_commit :add_secret_code, on: :create, unless: :admin?
  end

  def add_secret_code
    self.secret_code = valid_code
  end

  def valid_code?
    errors.add(:code, "invalid code") unless valid_code
  end

  def valid_code
    SecretCode.where(code: self.code, user: nil).first
  end
end

app/models/secret_code.rb
class SecretCode < ApplicationRecord
  belongs_to :user, optional: true
  validates :code, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  include Codeable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :secret_code

  def admin?
    role == "admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseWhitelist

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :code])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/secret_codes_controller.rb
require 'securerandom'

class SecretCodesController < ApplicationController
  load_and_authorize_resource
  before_action :set_secret_code, only: [:destroy]

  def index
    @secret_codes = SecretCode.all
  end

  def destroy
    @secret_code.destroy
    respond_to do |format|
      format.html { redirect_to secret_codes_url, notice: 'Secret code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def generate
    params[:quantity].to_i.times do
      SecretCode.create(code: SecureRandom.hex(10))
    end
    redirect_to secret_codes_url, notice: 'Secret codes has been generated successfully.'
  end

  private

  def set_secret_code
    @secret_code = SecretCode.find(params[:id])
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :success then "alert alert-success"
    when :notice then "alert alert-success"
    when :alert then "alert alert-danger"
    when :error then "alert alert-error"
    when :warning then "alert alert-warning"
    end
  end
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form_group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretCode Assignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/secret_codes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Secret Codes</h1>
      <div class="row">
        <div class="col-md-4">
          <h5 class="font-weight-bold">Select number to generate codes</h5>
        </div>
        <div class="col-md-4">
          <%= form_tag generate_secret_codes_path, method: :post do %>
            <div class="form-group">
              <%= select_tag :quantity, options_for_select([1, 10, 20, 50, 100], 10), {class: "form-control"} %>
            </div>
            <div class="form-group">
              <%= submit_tag "Generate Codes", class: "btn btn-primary" %>
            </div>
          <% end %>

        </div>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Code</th>
            <th>User</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @secret_codes.each do |secret_code| %>
            <tr>
              <td><%= secret_code.code %></td>
              <td><%= secret_code.try(:user).try(:email) %></td>
              <td><%= link_to 'Destroy', secret_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<div id="flash" class='text-center'>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %>" style="margin-bottom:0">
      <% unless value == true  %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= value %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "Home", root_path, class: 'nav-link active' %>
    </li>
    <% if can? :read, SecretCode %>
      <li class="nav-item">
        <%= link_to "Secret Codes", secret_codes_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li class="nav-item">
       <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger rounded-0" %>
      </li>
    <% else %>
      <li class="nav-item pull-right">
        <%= link_to 'Login', new_user_session_path, class: "btn btn-primary"  %>
      </li>
      <li class="nav-item ml-2">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
      </li>
    <% end %>
  </ul>
</nav>